### ISSUE TITLE
Possible memory leak when calling fast_obj_read_with_callbacks()

### ISSUE THREAD

**Issue by cadenji** [thisistherk/fast_obj#30]
For example, in the following code snippet, **lines 1398** and **1449** return the function without freeing the allocated memory. These problems all happen when there is not enough memory, so is this intentional? 

I think this is a bug, we should make sure the temporary resources are properly released returning the function.

https://github.com/thisistherk/fast_obj/blob/d2c273248a5ecdbbe28391ef952e70f8413d4f66/fast_obj.h#L1389-L1449

**Comment by thisistherk** [comment]
Wouldn't say it was exactly intentional, more laziness, but to do the job properly it'd need to check every 'array_push' too.  And in practice, they don't fail - at least on a 64-bit OS you'll start swapping and everything will grind to a halt long before you run out of address space causing malloc to fail.  If it was safety critical code or something, then it'd probably be a different matter, but it's just an OBJ loader, so 🤷. 

So probably not something I'm going to fix, but happy for patches if you want a go :)
